applications:
- instances: 1
  timeout: 180
  name: Saarathi Services
  buildpacks:
  - java_buildpack
  path: ./target/saarathi-services-0.0.1-SNAPSHOT.jar
  disk_quota: 1G
  memory: 256M
  env:
    JAVA_OPTS: '-XX:ReservedCodeCacheSize=32M -XX:MaxDirectMemorySize=32M'
    JBP_CONFIG_OPEN_JDK_JRE: '[memory_calculator: {stack_threads: 30}]'

spring:
  jpa:
    show-sql: true
    hibernate:
    ddl-auto: none
	show-sql : true
    properties:
	hibernate.dialect : org.hibernate.dialect.PostgreSQLDialect
  datasource:
    #SPRING_DATASOURCE_URL environment variable will be something like -> jdbc:sqlserver://MySqlServer\\MyInstance:1433;DatabaseName=MyDbName;
    url: jdbc:postgresql://echo.db.elephantsql.com:5432/ovowtsay
    username: ovowtsay
    password: qIP5e87I6hI9KYMav-8n3yoHo7wOjYSw
    initialization-mode : always
    initialize : true
    schema : classpath:/schema.sql
    continue-on-error : true